// Copyright (c) 2025 Nick McClure (Protospatial). All Rights Reserved.

/**
 * @file N2CGraphExporterV2.h
 * @brief Exports a live Blueprint graph as "N2C Graph v2" JSON (docs/BLUEPRINT_CPP_BRIDGE.md §7, §9.1)
 */

#pragma once

#include "CoreMinimal.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "K2Node.h"
#include "Dom/JsonObject.h"

/**
 * @class FN2CGraphExporterV2
 * @brief Turns the selected nodes (or the whole focused graph) into a lossless N2C Graph v2 document
 *
 * Unlike the v1 translator (FN2CNodeTranslator), this exporter writes internal pin names, full
 * class paths, node positions and a "symbols" table, so its output can be round-tripped by the
 * v2 importer (P2). It is a self-contained new code path per docs/BLUEPRINT_CPP_BRIDGE.md §8.1 and
 * does not share state or bugs with the v1 translator.
 */
class FN2CGraphExporterV2
{
public:
	/**
	 * Export a graph fragment as N2C Graph v2 JSON.
	 * @param Graph The graph the nodes live in (used for the graph "name"/"kind" and to resolve the owning Blueprint)
	 * @param SelectedNodes The nodes to export. Empty means "export the whole graph" (docs §9.1)
	 * @param bPrettyPrint Pretty-print (clipboard-friendly) vs condensed JSON
	 * @return The serialized document, or an empty string on failure
	 */
	static FString ExportGraph(UEdGraph* Graph, const TSet<UEdGraphNode*>& SelectedNodes, bool bPrettyPrint = true);

private:
	struct FExportContext
	{
		UEdGraph* Graph = nullptr;
		UBlueprint* Blueprint = nullptr;
		/** Nodes actually being exported (K2 nodes only; comment boxes are handled separately) */
		TArray<UK2Node*> Nodes;
		/** Stable, human-readable id assigned to each exported node */
		TMap<UK2Node*, FString> NodeIds;
		/** function symbol key ("/Script/Pkg.Class:Function") -> JSON facts, §12.2.3 */
		TSharedPtr<FJsonObject> FunctionSymbols;
		/** variable symbol key ("self:Name" / "local:Name" / "ClassPath:Name") -> JSON facts */
		TSharedPtr<FJsonObject> VariableSymbols;
		/** struct symbol key (struct path) -> JSON facts */
		TSharedPtr<FJsonObject> StructSymbols;
	};

	/** Assign stable, readable ids ("print_string_1") to every node, in Graph->Nodes order */
	static void AssignNodeIds(FExportContext& Ctx);

	/** Build the node id base name (before the uniquifying counter) for a given node */
	static FString MakeIdBase(UK2Node* Node);

	/** Convert an arbitrary display/identifier string to snake_case */
	static FString ToSnakeCase(const FString& In);

	/** Build the JSON object for a single node, filling kind + kind-specific fields (§7.4) */
	static TSharedPtr<FJsonObject> BuildNodeJson(FExportContext& Ctx, UK2Node* Node);

	/** Generic fallback for any node without a friendly v2 kind (§7.4 "k2node") */
	static void FillK2NodeFallback(UK2Node* Node, const TSharedPtr<FJsonObject>& NodeJson);

	/** Fill the "defaults" map: unconnected, non-autogenerated input pin values (§9.1) */
	static void FillDefaults(UK2Node* Node, const TSharedPtr<FJsonObject>& NodeJson);

	/** Read a pin's current value as an N2C Graph v2 default-value string (§7.8) */
	static FString GetPinDefaultValueString(const UEdGraphPin* Pin);

	/** Build the "links"/"external_links" arrays and the verbose "types" map */
	static void BuildLinks(FExportContext& Ctx, const TSharedPtr<FJsonObject>& GraphJson);

	/** Build the "comments" array for comment boxes that contain at least one exported node */
	static void BuildComments(FExportContext& Ctx, const TSharedPtr<FJsonObject>& GraphJson);

	/** Record symbol-table facts (§12.2.3) for a call_function node */
	static void RecordFunctionSymbol(FExportContext& Ctx, class UK2Node_CallFunction* FuncNode);

	/** Record symbol-table facts for a variable_get/variable_set node */
	static void RecordVariableSymbol(FExportContext& Ctx, class UK2Node_Variable* VarNode);

	/** Record symbol-table facts for a struct referenced by a pin */
	static void RecordStructSymbol(FExportContext& Ctx, const UScriptStruct* Struct);

	/** Find the internal pin ref ("id.PinName") for a pin, or empty if its node isn't in NodeIds */
	static FString GetPinRef(FExportContext& Ctx, const UEdGraphPin* Pin);

	/** Human-readable, best-effort description of a pin owned by a node outside the export set */
	static FString DescribeExternalPin(const UEdGraphPin* Pin);
};
